spring:
  data:
    cassandra:
      keyspace-name: main
      schema-action: create-if-not-exists
      username: <client_id>
      password: <client_secret>
datastax:
  astra:
    secure-connect-bundle: secure-connect.zip
